### ISSUE TITLE
NPM packaging for y-dom

### ISSUE THREAD

**Issue by jayaddison** [yjs/y-dom#2]
**Describe the bug**
The `y-dom` package looks useful for `yjs`-to-`html` element binding, but isn't yet available as a packaged module via NPM.

**Comment by dmonad** [comment]
Hi @jayaddison ,

I don't want to maintain the y-dom package anymore. Maintenance is a lot of work and I need to scale back. I maintain a lot of packages actively with little compensation. I can imagine only a few people would be interested in y-dom. You are free to learn from the code and re-implement the approach for Yjs v13. But it really just binds a Yjs document to HTML and requires more work to be generally useful. 

I recommend using an established editor like ProseMirror or Quill instead. If you want to build your own editor, you can use the Yjs document as a data-model. The pure HTML representation is too hard to work with for most use-cases.

**Comment by jayaddison** [comment]
No problem, thanks for the response and explanation @dmonad - I'll look into using one of the other editor base libraries.
